# Generated by Django 5.1.3 on 2024-11-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_image',
            field=models.ImageField(default=' ', upload_to='static/'),
        ),
    ]
